### ISSUE TITLE
Educative.io Course on Advanced Monitoring / Logging

### ISSUE THREAD

**Issue by JackTiber** [vfarcic/k8s-specs#17]
Recently signed up for the Advanced Kubernetes Techniques: Monitoring, Logging, Auto-Scaling course with educative.io and so far really liking the walk through of how to configure more detailed metrics and logging tools. Have ran into a couple of issues so far and just wanted to let you know they are out there.

1. When you are running a local kube cluster, regardless of if I used it with k3s, microk8s, or kubeadm, with a non-public cluster, or with a cluster that is using a self-signed cert (like when deploying with KubeSpray), the metrics-server fails to setup. The issue is in metrics-server itself as it expects that the certs be issued by a valid CA. Adding the --kubelet-insecure-tls flag fixes the issue and is explored here, but took a minute to find and would be confusing for anyone not running on a public cluster. Link to issue where the flag is explained and a walk through to setup certs that will work [here.](https://github.com/kubernetes-sigs/metrics-server/issues/146)
2. For the next section on Horizontal Auto-Scaling, the first example of the go-demo app (go-demo-5-no-sidecar-mem.yml) fails to setup on a local cluster. The error thrown in logs is:
```panic: no reachable servers

goroutine 1 [running]:
main.setupDb()
	/home/jenkins/workspace/go-demo-5_master-PUGTP37ZPAXQ7QFVCZOSPGHDUP64R2OHAFU6ZBGYY43JK5YVI5GA/main.go:68 +0x2b4
main.main()
	/home/jenkins/workspace/go-demo-5_master-PUGTP37ZPAXQ7QFVCZOSPGHDUP64R2OHAFU6ZBGYY43JK5YVI5GA/main.go:47 +0x49
```
Even with the above still really enjoying things and hope to get through the rest of the course soon.

**Comment by vfarcic** [comment]
Thank you for those notes. They are indeed very helpful.

I'll go through it later today and get back to you.

**Comment by anuragdev101** [comment]
Did you get time to look at it?

**Comment by nRookie** [comment]
any updates about this issue?  ran into the same problem.

committed a pull request to fix the issue here,
https://github.com/vfarcic/k8s-specs/pull/21

have time to look at it?
Really enjoy the course.

**Comment by vfarcic** [comment]
Sorry for not responding earlier. The notification of the previous comment got lost in the sea of emails I'm getting.

I went through the PR and approved it. Thanks a ton.

**Comment by Gianluca755** [comment]
Same problem, any news?

**Comment by vfarcic** [comment]
The PR #21 was merged. Are you experiencing issues with the latest version of the repo @Gianluca755?

**Comment by Gianluca755** [comment]
Yes with go-demo-5-no-sidecar-mem.yml, but I don't have access to educative.io anymore

**Comment by vfarcic** [comment]
I can go through it and see whether it needs updates. Can you please let me know where that file is @Gianluca755? I could not find it in this repo so I'm not sure where to look for it.

**Comment by Gianluca755** [comment]
@vfarcic the file go-demo-5-no-sidecar-mem.yml is in the scaling folder. Tested now in minikube and kubectl logs gives
```
goroutine 1 [running]:
main.setupDb()
	/home/jenkins/workspace/go-demo-5_master-PUGTP37ZPAXQ7QFVCZOSPGHDUP64R2OHAFU6ZBGYY43JK5YVI5GA/main.go:68 +0x2b4
main.main()
	/home/jenkins/workspace/go-demo-5_master-PUGTP37ZPAXQ7QFVCZOSPGHDUP64R2OHAFU6ZBGYY43JK5YVI5GA/main.go:47 +0x49
```
So the api Deployment has some broken container.

**Comment by vfarcic** [comment]
I just went through that whole section.

You're right @Gianluca755. As a matter of fact, there are quite a few other things broken in that section of the book/course alone. Too many things changed since years ago when I created that material. That's why I removed it a long time ago from all the places that I'm in control of. Educative choose to ignore my removal requests and committed to keep it up-to-date themselves which, from what I saw, is not the case.

Even though that's fully in the hands of the Educative (the maintenance of the course), I feel bad for the experience you had. How about an hour session during which I'll answer whichever questions you might have or help you might need? If that sounds good, please pick whichever time works for you from https://calendly.com/vfarcic/meet.

**Comment by Gianluca755** [comment]
Thank you @vfarcic for the kind offer, I appreciate it but it is not needed.
Wish you the best, bye
